project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_API_TOKEN
base_path: .
preserve_hierarchy: true
files:
  - source: /web/src/locales/en.json
    translation: /web/src/locales/%locale_with_underscore%.json
  - source: /api/src/i18n/en.json
    translation: /api/src/i18n/%locale%.json
