project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_API_TOKEN
base_path: .
preserve_hierarchy: true

files:
  # Frontend translations
  - source: /web/src/locales/en_US.json
    translation: /web/src/locales/%locale%.json
    type: json
    update_option: update_as_unapproved
    skip_untranslated_strings: false
    export_only_approved: false
    
  # Backend translations
  - source: /api/src/i18n/en/common.json
    translation: /api/src/i18n/%two_letters_code%/%file_name%.json
    type: json
    update_option: update_as_unapproved
    skip_untranslated_strings: false
    export_only_approved: false
    
  - source: /api/src/i18n/en/errors.json
    translation: /api/src/i18n/%two_letters_code%/%file_name%.json
    type: json
    update_option: update_as_unapproved
    skip_untranslated_strings: false
    export_only_approved: false
    
  - source: /api/src/i18n/en/validation.json
    translation: /api/src/i18n/%two_letters_code%/%file_name%.json
    type: json
    update_option: update_as_unapproved
    skip_untranslated_strings: false
    export_only_approved: false