version: '3.8'

x-development-volumes: &development-volumes
  volumes:
  - ./src:/app/src
  # Don't mount package-json in development since it's currently on 
  # a different node version - the copied one will be modified instead
  - ./tsconfig.json:/app/tsconfig.json
  - ./dist/:/app/dist/

x-production-volumes: &production-volumes
  volumes:
  - ./src:/app/src
  - ./package.json:/app/package.json
  - ./package-lock.json:/app/package-lock.json
  - ./tsconfig.json:/app/tsconfig.json
  - ./dist/:/app/dist/

services: 
  interactive:
    image: unraid-api-node-18
    build: 
      context: .
      dockerfile: Dockerfile
      args: 
        NODE_IMAGE: node:18
        NODE_ENV: development
        NPM_I_CMD: npm i
    <<: *development-volumes
    stdin_open: true
    tty: true
    platform: linux/amd64
    entrypoint: /bin/bash
    profiles:
      - interactive
  builder-interactive:
    image: unraid-api-node-14
    build: 
      context: .
      dockerfile: Dockerfile
      args: 
        NODE_IMAGE: node:14.15.3
        NODE_ENV: production
        NPM_I_CMD: npm ci
    <<: *production-volumes
    platform: linux/amd64
    stdin_open: true
    tty: true
    entrypoint: /bin/bash
    profiles:
      - builder
  builder:
    image: unraid-api-node-14
    build: 
      context: .
      dockerfile: Dockerfile
      args: 
        NODE_IMAGE: node:14.15.3
        NODE_ENV: production
        NPM_I_CMD: npm ci
    <<: *production-volumes
    platform: linux/amd64
    command: "npm run build && npm run build-binary && mv ./unraid-api ~/dist/unraid-api"
    profiles:
      - builder