version: '3.8'

x-development-volumes: &development-volumes
  volumes:
  - ./src:/app/src
  - ./package.json:/app/package.json
  - ./package-lock.json:/app/package-lock.json
  - ./tsconfig.json:/app/tsconfig.json
  - ./dist/:/app/dist/

services: 
  image: 
    image: unraid-api
    build:
      context: .
      dockerfile: Dockerfile
    profiles:
      - builder
      - interactive
  interactive:
    image: unraid-api
    depends_on: 
      - image
    <<: *development-volumes
    stdin_open: true
    tty: true
    platform: linux/amd64
    entrypoint: /bin/bash
    profiles:
      - interactive

  builder:
    image: unraid-api
    depends_on:
      - image
    <<: *development-volumes
    platform: linux/amd64
    command: "npm run build-binary"
    profiles:
      - builder