export enum API_KEY_STATUS {
	NO_API_KEY = 'NO_API_KEY',
	PENDING_VALIDATION = 'PENDING_VALIDATION',
	NETWORK_ERROR = 'NETWORK_ERROR',
	INVALID_KEYSERVER_RESPONSE = 'INVALID_KEYSERVER_RESPONSE',
	API_KEY_VALID = 'API_KEY_VALID',
	API_KEY_INVALID = 'API_KEY_INVALID',
}
