import { test, expect, vi } from 'vitest';

vi.mock('@app/core/pubsub', () => ({
    pubsub: { publish: vi.fn() },
}));

test('Creates an array event', async () => {
    const { getArrayData } = await import(
        '@app/core/modules/array/get-array-data'
    );
    const { store } = await import('@app/store');
    const { loadStateFiles } = await import('@app/store/modules/emhttp');

    // Load state files into store
    await store.dispatch(loadStateFiles());

    const arrayEvent = getArrayData(store.getState);
    expect(arrayEvent).toMatchInlineSnapshot(`
      {
        "boot": {
          "comment": "Unraid OS boot device",
          "critical": null,
          "device": "sda",
          "exportable": true,
          "format": "unknown",
          "fsFree": 3116608,
          "fsSize": 3947980,
          "fsType": "vfat",
          "fsUsed": 831372,
          "id": "Cruzer",
          "idx": 32,
          "name": "flash",
          "numErrors": 0,
          "numReads": 0,
          "numWrites": 0,
          "rotational": true,
          "size": 3956700,
          "status": "DISK_OK",
          "temp": null,
          "transport": "usb",
          "type": "Flash",
          "warning": null,
        },
        "caches": [
          {
            "comment": "",
            "critical": null,
            "device": "sdi",
            "exportable": false,
            "format": "MBR: 4KiB-aligned",
            "fsFree": 109190120,
            "fsSize": 244198552,
            "fsType": "btrfs",
            "fsUsed": 134056472,
            "id": "Samsung_SSD_850_EVO_250GB_S2R5NX0H643734Z",
            "idx": 30,
            "name": "cache",
            "numErrors": 0,
            "numReads": 0,
            "numWrites": 0,
            "rotational": false,
            "size": 244198552,
            "status": "DISK_OK",
            "temp": 22,
            "transport": "ata",
            "type": "Cache",
            "warning": null,
          },
          {
            "comment": null,
            "critical": null,
            "device": "nvme0n1",
            "exportable": false,
            "format": "MBR: 4KiB-aligned",
            "fsFree": null,
            "fsSize": null,
            "fsType": null,
            "fsUsed": null,
            "id": "KINGSTON_SA2000M8250G_50026B7282669D9E",
            "idx": 31,
            "name": "cache2",
            "numErrors": 0,
            "numReads": 0,
            "numWrites": 0,
            "rotational": false,
            "size": 244198552,
            "status": "DISK_OK",
            "temp": 27,
            "transport": "nvme",
            "type": "Cache",
            "warning": null,
          },
        ],
        "capacity": {
          "disks": {
            "free": "27",
            "total": "30",
            "used": "3",
          },
          "kibibytes": {
            "free": "19038892160",
            "total": "41010494044",
            "used": "21971601884",
          },
        },
        "disks": [
          {
            "comment": "Seagate Exos",
            "critical": 75,
            "device": "sdf",
            "exportable": false,
            "format": "GPT: 4KiB-aligned",
            "fsFree": 13557363020,
            "fsSize": 17576897220,
            "fsType": "xfs",
            "fsUsed": 4019534200,
            "id": "ST18000NM000J-2TV103_ZR5B1W9X",
            "idx": 1,
            "name": "disk1",
            "numErrors": 0,
            "numReads": 0,
            "numWrites": 0,
            "rotational": true,
            "size": 17578328012,
            "status": "DISK_OK",
            "temp": 30,
            "transport": "ata",
            "type": "Data",
            "warning": 50,
          },
          {
            "comment": "",
            "critical": null,
            "device": "sdj",
            "exportable": false,
            "format": "GPT: 4KiB-aligned",
            "fsFree": 90957760,
            "fsSize": 11716798412,
            "fsType": "xfs",
            "fsUsed": 11625840652,
            "id": "WDC_WD120EDAZ-11F3RA0_5PJRD45C",
            "idx": 2,
            "name": "disk2",
            "numErrors": 0,
            "numReads": 0,
            "numWrites": 0,
            "rotational": true,
            "size": 11718885324,
            "status": "DISK_OK",
            "temp": 30,
            "transport": "ata",
            "type": "Data",
            "warning": null,
          },
          {
            "comment": "",
            "critical": null,
            "device": "sde",
            "exportable": false,
            "format": "GPT: 4KiB-aligned",
            "fsFree": 5390571380,
            "fsSize": 11716798412,
            "fsType": "xfs",
            "fsUsed": 6326227032,
            "id": "WDC_WD120EMAZ-11BLFA0_5PH8BTYD",
            "idx": 3,
            "name": "disk3",
            "numErrors": 0,
            "numReads": 0,
            "numWrites": 0,
            "rotational": true,
            "size": 11718885324,
            "status": "DISK_OK",
            "temp": 30,
            "transport": "ata",
            "type": "Data",
            "warning": null,
          },
        ],
        "parities": [
          {
            "comment": null,
            "critical": null,
            "device": "sdh",
            "exportable": false,
            "format": "GPT: 4KiB-aligned",
            "fsFree": null,
            "fsSize": null,
            "fsType": null,
            "fsUsed": null,
            "id": "ST18000NM000J-2TV103_ZR585CPY",
            "idx": 0,
            "name": "parity",
            "numErrors": 0,
            "numReads": 0,
            "numWrites": 0,
            "rotational": true,
            "size": 17578328012,
            "status": "DISK_OK",
            "temp": 25,
            "transport": "ata",
            "type": "Parity",
            "warning": null,
          },
        ],
        "state": "STOPPED",
      }
    `);
});
