/** The Dependency Injection token for the GRAPHQL_PUB_SUB event bus. */
export const GRAPHQL_PUBSUB_TOKEN = "GRAPHQL_PUBSUB";

/** PUBSUB_CHANNELS enum for the GRAPHQL_PUB_SUB event bus */
export enum GRAPHQL_PUBSUB_CHANNEL {
  ARRAY = "ARRAY",
  CPU_UTILIZATION = "CPU_UTILIZATION",
  DASHBOARD = "DASHBOARD",
  DISPLAY = "DISPLAY",
  INFO = "INFO",
  NOTIFICATION = "NOTIFICATION",
  NOTIFICATION_ADDED = "NOTIFICATION_ADDED",
  NOTIFICATION_OVERVIEW = "NOTIFICATION_OVERVIEW",
  OWNER = "OWNER",
  SERVERS = "SERVERS",
  VMS = "VMS",
  LOG_FILE = "LOG_FILE",
  PARITY = "PARITY",
}
