/** The Dependency Injection token for the GRAPHQL_PUB_SUB event bus. */
export const GRAPHQL_PUBSUB_TOKEN = "GRAPHQL_PUBSUB";

/** PUBSUB_CHANNELS enum for the GRAPHQL_PUB_SUB event bus */
export enum GRAPHQL_PUBSUB_CHANNEL {
  ARRAY = "ARRAY",
  CPU_UTILIZATION = "CPU_UTILIZATION",
  CPU_TELEMETRY = "CPU_TELEMETRY",
  DASHBOARD = "DASHBOARD",
  DISPLAY = "DISPLAY",
  INFO = "INFO",
  MEMORY_UTILIZATION = "MEMORY_UTILIZATION",
  NOTIFICATION = "NOTIFICATION",
  NOTIFICATION_ADDED = "NOTIFICATION_ADDED",
  NOTIFICATION_OVERVIEW = "NOTIFICATION_OVERVIEW",
  NOTIFICATION_WARNINGS_AND_ALERTS = "NOTIFICATION_WARNINGS_AND_ALERTS",
  OWNER = "OWNER",
  SERVERS = "SERVERS",
  TEMPERATURE_METRICS = "TEMPERATURE_METRICS",
  VMS = "VMS",
  DOCKER_STATS = "DOCKER_STATS",
  LOG_FILE = "LOG_FILE",
  PARITY = "PARITY",
}
