export enum StateFileKey {
    DISPLAY = 'display',
    DISKS = 'disks',
    DOCKER = 'docker',
    EMHTTP = 'emhttp',
    IDENT = 'ident',
    SHARES = 'shares',
    SLOTS = 'slots',
    USERS = 'users',
    DEVICES = 'devices',
    NETWORK = 'network',
    NFS = 'nfs',
    NGINX = 'nginx',
    SMB = 'smb',
    VAR = 'var',
    SEC = 'sec',
    NOTIFICATION = 'notification',
} 