export const BASE_POLICY = `
# Admin permissions
p, ADMIN, *, *, *

# UPC permissions for API keys
p, UPC, API_KEY, CREATE, ANY
p, UPC, API_KEY, UPDATE, ANY

# UPC permissions
p, UPC, CLOUD, READ, OWN
p, UPC, CONFIG, READ, ANY
p, UPC, crash-reporting-enabled, READ, ANY
p, UPC, CUSTOMIZATIONS, READ, ANY
p, UPC, DISK, READ, ANY
p, UPC, DISPLAY, READ, ANY
p, UPC, FLASH, READ, ANY
p, UPC, INFO, READ, ANY
p, UPC, LOGS, READ, ANY
p, UPC, OS, READ, ANY
p, UPC, OWNER, READ, ANY
p, UPC, REGISTRATION, READ, ANY
p, UPC, SERVERS, READ, ANY
p, UPC, VARS, READ, ANY
p, UPC, CONFIG, UPDATE, OWN
p, UPC, CONNECT, READ, OWN
p, UPC, CONNECT, UPDATE, OWN
p, UPC, NOTIFICATIONS, READ, ANY
p, UPC, NOTIFICATIONS, UPDATE, ANY

# My Servers permissions
p, MY_SERVERS, ARRAY, READ, ANY
p, MY_SERVERS, CONFIG, READ, ANY
p, MY_SERVERS, CONNECT, READ, ANY
p, MY_SERVERS, connect/dynamic-remote-access, READ, ANY
p, MY_SERVERS, connect/dynamic-remote-access, UPDATE, OWN
p, MY_SERVERS, CUSTOMIZATIONS, READ, ANY
p, MY_SERVERS, DASHBOARD, READ, ANY
p, MY_SERVERS, DISPLAY, READ, ANY
p, MY_SERVERS, docker/container, READ, ANY
p, MY_SERVERS, DOCKER, READ, ANY
p, MY_SERVERS, INFO, READ, ANY
p, MY_SERVERS, LOGS, READ, ANY
p, MY_SERVERS, NETWORK, READ, ANY
p, MY_SERVERS, NOTIFICATIONS, READ, ANY
p, MY_SERVERS, SERVICES, READ, ANY
p, MY_SERVERS, VARS, READ, ANY
p, MY_SERVERS, VMS, READ, ANY
p, MY_SERVERS, vms/domain, READ, ANY
p, MY_SERVERS, unraid-version, READ, ANY

# Notifier permissions
p, NOTIFIER, NOTIFICATIONS, CREATE, OWN

# Guest permissions
p, GUEST, ME, READ, ANY
p, GUEST, WELCOME, READ, ANY

# Role inheritance
g, ADMIN, GUEST
g, UPC, GUEST
g, MY_SERVERS, GUEST
g, NOTIFIER, GUEST
`;
