default: list-commands

list-commands:
    @just --list --justfile {{justfile()}} --list-heading $'\nMonorepo recipes:\n'  

# Prepares the repo for development
setup:
    npm install
    npm run build

clean:
    npm run clean
    rm -rf node_modules

build-wc:
    REM_PLUGIN=true vite build -c vite.web-component.ts --mode production

deploy server_name:
    rsync -avz -e ssh ./dist/ root@{{server_name}}:/usr/local/emhttp/plugins/dynamix.my.servers/unraid-components