set fallback

default:
    @just --list --justfile {{justfile()}} --list-heading $'\nAPI project recipes:\n'
    @just list-commands

# builds js files that can run on an unraid server
@build:
    pnpm run build

# deploys to an unraid server
@deploy:
    ./scripts/deploy-dev.sh

# build & deploy
bd: build deploy
