name: 'Delete old artifacts'

on:
  schedule:
    - cron: '0 0 * * 6' # every saturday at midnight

jobs:
  delete-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: kolpav/purge-artifacts-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # Keep the last 7 day's worth of builds
          expire-in: 7day # Setting this to 0 will delete all artifacts
