name: Manual Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., 4.25.3)'
        required: true
        type: string
      target_commitish:
        description: 'Commit SHA or branch (leave empty for current HEAD)'
        required: false
        type: string
      release_notes:
        description: 'Release notes/changelog'
        required: false
        type: string
        default: 'Manual release'
      prerelease:
        description: 'Mark as prerelease'
        required: false
        type: boolean
        default: false

permissions:
  contents: write
  pull-requests: write

jobs:
  build-artifacts:
    name: Build All Artifacts
    uses: ./.github/workflows/build-artifacts.yml
    with:
      ref: ${{ inputs.target_commitish || github.ref }}
      version_override: ${{ inputs.version }}
    secrets:
      VITE_ACCOUNT: ${{ secrets.VITE_ACCOUNT }}
      VITE_CONNECT: ${{ secrets.VITE_CONNECT }}
      VITE_UNRAID_NET: ${{ secrets.VITE_UNRAID_NET }}
      VITE_CALLBACK_KEY: ${{ secrets.VITE_CALLBACK_KEY }}
      UNRAID_BOT_GITHUB_ADMIN_TOKEN: ${{ secrets.UNRAID_BOT_GITHUB_ADMIN_TOKEN }}

  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs:
      - build-artifacts
    outputs:
      tag_name: ${{ steps.create_release.outputs.tag_name }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5
        with:
          ref: ${{ inputs.target_commitish || github.ref }}
          fetch-depth: 0

      - name: Create or Update Release
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG_NAME="v${{ inputs.version }}"
          TARGET="${{ inputs.target_commitish || github.sha }}"
          
          echo "tag_name=${TAG_NAME}" >> $GITHUB_OUTPUT
          
          if gh release view "${TAG_NAME}" > /dev/null 2>&1; then
            echo "Release ${TAG_NAME} already exists, updating..."
            gh release edit "${TAG_NAME}" \
              --notes "${{ inputs.release_notes }}" \
              ${{ inputs.prerelease && '--prerelease' || '' }}
          else
            echo "Creating new release ${TAG_NAME}..."
            git tag "${TAG_NAME}" "${TARGET}" || true
            git push origin "${TAG_NAME}" || true
            
            gh release create "${TAG_NAME}" \
              --title "${{ inputs.version }}" \
              --notes "${{ inputs.release_notes }}" \
              --target "${TARGET}" \
              ${{ inputs.prerelease && '--prerelease' || '' }}
          fi

  build-plugin-production:
    name: Build and Deploy Production Plugin
    needs:
      - create-release
      - build-artifacts
    uses: ./.github/workflows/build-plugin.yml
    with:
      RELEASE_CREATED: true
      RELEASE_TAG: ${{ needs.create-release.outputs.tag_name }}
      TAG: ""
      BUCKET_PATH: unraid-api
      BASE_URL: "https://stable.dl.unraid.net/unraid-api"
      BUILD_NUMBER: ${{ needs.build-artifacts.outputs.build_number }}
    secrets:
      CF_ACCESS_KEY_ID: ${{ secrets.CF_ACCESS_KEY_ID }}
      CF_SECRET_ACCESS_KEY: ${{ secrets.CF_SECRET_ACCESS_KEY }}
      CF_BUCKET_PREVIEW: ${{ secrets.CF_BUCKET_PREVIEW }}
      CF_ENDPOINT: ${{ secrets.CF_ENDPOINT }}
      UNRAID_BOT_GITHUB_ADMIN_TOKEN: ${{ secrets.UNRAID_BOT_GITHUB_ADMIN_TOKEN }}

