name: CI - Main (Plugin) 

on:
  push:
    branches:
      - master
    paths-ignore:
      - api
      - "**.md"
defaults:
  run:
    working-directory: plugin
jobs:
  start: 
    # This prevents a tag running twice as it'll have a "tag" and a "commit" event
    # We only want the tag to run the action as it'll be able to create the release notes
    if: (startsWith(github.event.ref, 'refs/heads/') && !startsWith(github.event.head_commit.message, 'chore(release)')) || (startsWith(github.event.ref, 'refs/tags/') && startsWith(github.event.head_commit.message, 'chore(release)'))
    runs-on: ubuntu-latest
    steps:
      - name: Validate branch and tag
        run: exit 0
        working-directory: /
  Auto-Builder:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Build tgz and plgs
        run: |
          cd source/dynamix.unraid.net
          bash ./pkg_build.sh s
          bash ./pkg_build.sh p

      - name: Upload binary txz and plg to Github artifacts
        uses: actions/upload-artifact@v3
        with:
          name: connect-files
          path: |
            ${{ github.workspace }}/plugin/archive/*.txz
            ${{ github.workspace }}/plugin/plugins/*.plg
          retention-days: 5
          if-no-files-found: error

      - name: Upload staging txz to DigitalOcean Spaces
        uses: BetaHuhn/do-spaces-action@v2
        with:
          access_key: ${{ secrets.DO_ACCESS_KEY }}
          secret_key: ${{ secrets.DO_SECRET_KEY }}
          space_name: ${{ secrets.DO_SPACE_NAME }}
          space_region: ${{ secrets.DO_SPACE_REGION }}
          source: archive/dynamix.unraid.net.staging.txz
          out_dir: unraid-api

      - name: Upload staging plg to DigitalOcean Spaces
        uses: BetaHuhn/do-spaces-action@v2
        with:
          access_key: ${{ secrets.DO_ACCESS_KEY }}
          secret_key: ${{ secrets.DO_SECRET_KEY }}
          space_name: ${{ secrets.DO_SPACE_NAME }}
          space_region: ${{ secrets.DO_SPACE_REGION }}
          source: plugins/dynamix.unraid.net.staging.plg
          out_dir: unraid-api
