name: Pull Request Web

on:
  pull_request:
    paths:
      - 'web/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}-web
  cancel-in-progress: true

jobs:
  lint-web:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Lint, Test, and Build Web Components
        uses: ./.github/workflows/lint-test-build-web.yml
