set fallback

default:
    @just --list --justfile {{justfile()}} --list-heading $'\nWeb project recipes:\n'
    @just list-commands

setup:
    just ../unraid-ui/setup
    cp .env.example .env
    npm install

clean:
    rm -rf .nuxt
    rm -rf node_modules
